name: Push

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...